services:
  # ========================
  # ⚙️ Gluetun - VPN client
  # ========================
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - DNS_ADDRESS=${DNS_ADDRESS}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CITIES=${SERVER_CITIES}
      - TZ=${TZ}
    ports:
      - "8080:8080"     # qBittorrent web UI
      - "6881:6881"     # Torrent TCP
      - "6881:6881/udp" # Torrent UDP
    restart: unless-stopped

  # ========================
  # 📥 qBittorrent - Torrent client
  # ========================
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=8080
    volumes:
      - ${MEDIA_PATH}/downloads:/downloads
      - ${CONFIG_PATH}/qbittorrent:/config
    restart: unless-stopped
